name = "CallableModules"
uuid = "bc93ac54-acd5-5963-b2b8-c9289e02c1c6"
authors = ["Patrick Häcker <patrick.haecker@de.bosch.com>"]
version = "0.1.0"

[workspace]
projects = ["test", "docs"]

[compat]
julia = "1.10"
